// nuxt/components/Todo.vue
<script setup lang="ts">
const props = defineProps(["id", "title", "done", "refresh"]);

async function checkTodo(event: Event) {
  await $fetch("/api/complete?id=" + props.id, {
    method: "POST",
    body: {
      done: (event.target as HTMLInputElement).checked,
    },
  });

  props.refresh();
}
</script>

<template>
  <div class="flex flex-row gap-1 items-center p-1">
    <input :checked="props.done" type="checkbox" @change="checkTodo" />
    <p :class="{ 'line-through': $props.done }">{{ $props.title }}</p>
  </div>
</template>

// next/prisma/src/components/Todo.tsx
"use client";

import type { Todo } from "@prisma/client";

export default function Todo({ todo }: { todo: Todo }) {
  return (
    <div className="flex flex-row gap-1 items-center p-1">
      <input
        type="checkbox"
        checked={todo.done}
        onChange={() => {
          const formData = new FormData();
          formData.append("done", (!todo.done).toString());

          fetch(`/api/complete?id=${todo.id}`, {
            method: "PATCH",
            body: formData,
          }).then(() => {
            location.reload();
          });
        }}
      />
      <p className={todo.done ? "line-through" : ""}>{todo.title}</p>
    </div>
  );
}
